docs: Fix EventEmitter initialization example (#245)
## Description

We should consider using `new` keyword to properly instantiate EventEmitter class object, otherwise we get an error (as per current docs example):
```js
const eventEmitter = require('events').EventEmitter()
eventEmitter.on('start', () => {
  console.log('started')
})
```
ends up with:
```
TypeError: Cannot read property 'on' of undefined
```

Whereas instantiating with `new`:
```js
const EventEmitter = require('events')                                          
const eventEmitter = new EventEmitter()

console.log(eventEmitter instanceof EventEmitter) // true

eventEmitter.on('start', () => {
  console.log('started')
})
eventEmitter.emit('start')
```
outputs:
```
true
started
```

## Related Issues

Fixes #242